# This is a basic workflow to help you get started with Actions
# Controls when the action will run. 
on:
  push:
    branches:
     - staging

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: sftp.pressable.com
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        server-dir: htdocs/wp-content/plugins/woocommerce-payfast-gateway/
